### ISSUE TITLE
Unable to run Training Sample Influence Estimation case study. Cuda assignment is having errors.

### ISSUE THREAD

**Issue by pearlmary** [JacksonWuxs/UsableXAI_LLM#1]

**Comment by JacksonWuxs** [comment]
Hi @pearlmary, 

Thanks for following this work! To adapt the code in your CUDA environment, you may need to specify the GPUs you want to use in [Line](https://github.com/JacksonWuxs/UsableXAI_LLM/blob/b89dbf06d1b36cb2c2538feb0388098ef9a738d4/Case_Studies/case_EKFAC_based_Influence_Estimation/evaluating_sample_influence.py#L15).

Thanks,
Xuansheng
