### ISSUE TITLE
How to get /data/weights/vicuna/hf_models/7B/? From where we need to download?

### ISSUE THREAD

**Issue by chowkamlee81** [JacksonWuxs/UsableXAI_LLM#2]
@JacksonWuxs 
How to get /data/weights/vicuna/hf_models/7B/? From where we need to download?

**Comment by JacksonWuxs** [comment]
Hi @chowkamlee81  

Thanks for following our work! 

Since Vicuna-v1.1 is based on Llama-1, we cannot share the weights of these models under their policy. We recommend changing the model to ``lmsys/vicuna-7b-v1.5`` or other instruction-tuned models from Huggingface. 

Thanks,
Xuansheng
